"""Fix nullable on task_labels

Revision ID: f453de9593b3
Revises: 2237a1a42848
Create Date: 2026-07-30 06:04:04.012333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f453de9593b3'
down_revision: Union[str, Sequence[str], None] = '2237a1a42848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_labels', schema=None) as batch_op:
        batch_op.alter_column('task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('label_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_labels', schema=None) as batch_op:
        batch_op.alter_column('label_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('task_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
